version: '3.4'

services:
  cms.ar.xarchitecture.de:
    image: ${DOCKER_REGISTRY-}cmsarxarchitecturede
    build:
      context: .
      dockerfile: cms.ar.xarchitecture.de/Dockerfile
    volumes:
      - ${ASSETS}:/app/wwwroot/content/assets
      - ${WORLDMAPS}:/app/wwwroot/content/worldmaps
      - ${MARKER}:/app/wwwroot/content/marker
      - ${THUMBS}:/app/wwwroot/content/thumbnails   