-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 22:15:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cmsDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cmsDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cmsDatabase` DEFAULT CHARACTER SET utf8 ;
USE `cmsDatabase` ;

-- -----------------------------------------------------
-- Table `cmsDatabase`.`Studies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`Studies` (
  `ProgrammeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Programme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProgrammeID`),
  UNIQUE INDEX `Studies_UNIQUE` (`Programme` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ProgrammeID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmsDatabase`.`Creator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`Creator` (
  `CreatorID` INT NOT NULL AUTO_INCREMENT,
  `Creator` VARCHAR(45) NOT NULL,
  `Programme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CreatorID`),
  UNIQUE INDEX `CreatorID_UNIQUE` (`CreatorID` ASC) VISIBLE,
  INDEX `fk_Creator_Studies1_idx` (`Programme` ASC) VISIBLE,
  CONSTRAINT `fk_Creator_Studies`
    FOREIGN KEY (`Programme`)
    REFERENCES `cmsDatabase`.`Studies` (`Programme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmsDatabase`.`Term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`Term` (
  `TermID` INT NOT NULL AUTO_INCREMENT,
  `Term` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TermID`),
  UNIQUE INDEX `Termn_UNIQUE` (`Term` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmsDatabase`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`Course` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `Programme` VARCHAR(45) NOT NULL,
  `Course` VARCHAR(45) NOT NULL,
  `Term` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CourseID`),
  UNIQUE INDEX `CourseID_UNIQUE` (`CourseID` ASC) VISIBLE,
  INDEX `fk_Course_Studies1_idx` (`Programme` ASC) VISIBLE,
  INDEX `fk_Course_Term1_idx` (`Term` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Studies`
    FOREIGN KEY (`Programme`)
    REFERENCES `cmsDatabase`.`Studies` (`Programme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Term1`
    FOREIGN KEY (`Term`)
    REFERENCES `cmsDatabase`.`Term` (`Term`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmsDatabase`.`Thumbnail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`Thumbnail` (
  `ThumbnailID` INT NOT NULL AUTO_INCREMENT,
  `ThumbnailUUID` VARCHAR(45) NULL,
  PRIMARY KEY (`ThumbnailID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmsDatabase`.`SceneAsset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`SceneAsset` (
  `AssetID` INT NOT NULL AUTO_INCREMENT,
  `Creator` INT NOT NULL,
  `Course` INT NOT NULL,
  `AssetName` VARCHAR(45) NULL,
  `FileUUID` VARCHAR(45) NULL,
  `ExternalLink` VARCHAR(45) NULL,
  `CreationData` DATETIME NULL,
  `ThumbnailUUID` VARCHAR(45) NULL COMMENT 'Also Link to File!',
  `Deleted` TINYINT NULL,
  PRIMARY KEY (`AssetID`),
  INDEX `fk_SceneAsset_Creator1_idx` (`Creator` ASC) VISIBLE,
  INDEX `fk_SceneAsset_Course1_idx` (`Course` ASC) VISIBLE,
  UNIQUE INDEX `AssetID_UNIQUE` (`AssetID` ASC) VISIBLE,
  INDEX `fk_SceneAsset_Thumbnail1_idx` (`ThumbnailUUID` ASC) VISIBLE,
  CONSTRAINT `fk_SceneAsset_Creator`
    FOREIGN KEY (`Creator`)
    REFERENCES `cmsDatabase`.`Creator` (`CreatorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SceneAsset_Course`
    FOREIGN KEY (`Course`)
    REFERENCES `cmsDatabase`.`Course` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SceneAsset_Thumbnail1`
    FOREIGN KEY (`ThumbnailUUID`)
    REFERENCES `cmsDatabase`.`Thumbnail` (`ThumbnailUUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmsDatabase`.`Scene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`Scene` (
  `SceneID` INT NOT NULL AUTO_INCREMENT,
  `SceneName` VARCHAR(45) NULL,
  `FileUUID` VARCHAR(45) NULL,
  `MarkerUUID` VARCHAR(45) NULL COMMENT 'UUID',
  PRIMARY KEY (`SceneID`),
  UNIQUE INDEX `SceneID_UNIQUE` (`SceneID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmsDatabase`.`Anchor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmsDatabase`.`Anchor` (
  `AnchorID` VARCHAR(45) NOT NULL,
  `AssetID` INT NOT NULL,
  `Scale` FLOAT NULL DEFAULT 1,
  PRIMARY KEY (`AnchorID`),
  INDEX `fk_Anchor_SceneAsset1_idx` (`AssetID` ASC) VISIBLE,
  UNIQUE INDEX `AnchorID_UNIQUE` (`AnchorID` ASC) VISIBLE,
  CONSTRAINT `fk_Anchor_SceneAsset`
    FOREIGN KEY (`AssetID`)
    REFERENCES `cmsDatabase`.`SceneAsset` (`AssetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
