name: Production CMS

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: docker login
        env:
          DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY_URL}}
          DOCKER_USER: ${{secrets.DOCKER_REGISTRY_USER}} 
          DOCKER_PASSWORD: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
        run: |
          docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build cms
        run: |
          docker build ./cms.ar.xarchitecture.de/cms.ar.xarchitecture.de -t ar-exhibition/cms:release
      - name: docker push image
        run: |
          docker push ar-exhibition/cms:release
